# Generated by Django 4.2.7 on 2025-07-17 12:30

import accommodations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='숙소명')),
                ('location', models.CharField(max_length=200, verbose_name='위치')),
                ('price', models.PositiveIntegerField(verbose_name='1박 가격')),
                ('description', models.TextField(verbose_name='설명')),
                ('check_in', models.TimeField(verbose_name='체크인 시간')),
                ('check_out', models.TimeField(verbose_name='체크아웃 시간')),
                ('amenities', models.JSONField(default=list, verbose_name='편의시설')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '숙소',
                'verbose_name_plural': '숙소들',
                'db_table': 'accommodations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accommodations.models.accommodation_image_path, verbose_name='이미지')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='이미지 설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.accommodation', verbose_name='숙소')),
            ],
            options={
                'verbose_name': '숙소 이미지',
                'verbose_name_plural': '숙소 이미지들',
                'db_table': 'accommodation_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
